"""Indicadores valiosos para gerencia que hoy NO pueden construirse, y qué dato los habilitaría."""

OPORTUNIDADES = [
    {"indicador": "Cumplimiento de meta de siniestralidad",
     "pregunta": "¿Estamos dentro de lo que la organización se propuso?",
     "falta": "Metas oficiales de tasa, costo o casos por periodo (y por sector o cliente, si aplica).",
     "hoy": "Los indicadores se comparan con su propio historial; no se muestra ningún % de cumplimiento."},
    {"indicador": "Costo real vs presupuesto",
     "pregunta": "¿El costo de la siniestralidad está dentro de lo presupuestado?",
     "falta": "Presupuesto mensual de costo de siniestralidad.",
     "hoy": "Solo se mide la variación del costo frente a periodos anteriores."},
    {"indicador": "Índice de frecuencia por horas trabajadas (IF por 1.000.000 h)",
     "pregunta": "¿Cuál es la frecuencia estándar comparable con referencias del sector?",
     "falta": "Horas hombre trabajadas (HHT) por cliente y mes.",
     "hoy": "Se usa casos por 100 trabajadores activos (definición oficial de la prueba)."},
    {"indicador": "Causas y tipo de evento",
     "pregunta": "¿Por qué ocurren los casos (caídas, golpes, sobreesfuerzo, tránsito…)?",
     "falta": "Clasificación del mecanismo, agente y parte del cuerpo de cada caso.",
     "hoy": "Solo se distingue leve/grave: el 'por qué' se aproxima con sector, clase de riesgo y prevención."},
    {"indicador": "Efectividad de la prevención",
     "pregunta": "¿Qué tipo de actividad de prevención reduce más los casos?",
     "falta": "Registro de asistencia por trabajador y una evaluación antes/después; idealmente un diseño comparativo.",
     "hoy": "Solo se muestra una asociación observada entre prevención y tasa (no causal)."},
    {"indicador": "Oportunidad de cierre de casos",
     "pregunta": "¿Cuánto tardamos en cerrar un caso y cuántos están represados?",
     "falta": "Fecha de cierre de cada caso (hoy solo se conoce el estado a la fecha de corte).",
     "hoy": "Se reporta cuántos casos graves siguen abiertos, sin tiempos."},
    {"indicador": "Rentabilidad por cliente",
     "pregunta": "¿Qué clientes son rentables considerando su siniestralidad?",
     "falta": "Confirmación de la base de valor_contrato (mensual, anual, prima) y de si el costo de los casos lo asume la empresa.",
     "hoy": "La relación costo/facturación se muestra solo como indicador descriptivo con advertencia."},
    {"indicador": "Cobertura de visitas del coordinador",
     "pregunta": "¿Los coordinadores visitan primero a los clientes con más riesgo?",
     "falta": "Registro de visitas o reuniones de seguimiento por cliente.",
     "hoy": "Se usa la prevención como aproximación del acompañamiento."},
    {"indicador": "Días cargados y severidad normativa",
     "pregunta": "¿Cuál es la severidad incluyendo secuelas y fatalidades?",
     "falta": "Días cargados por incapacidad permanente o muerte, y marca de accidente mortal.",
     "hoy": "La severidad usa solo días de ausencia registrados."},
]
