# Generated by Django 5.2.17 on 2026-09-25 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(default='Grupo SURA', max_length=120)),
                ('umbral_critico', models.DecimalField(decimal_places=2, default=5, help_text='Tasa por 100 trabajadores por encima de la cual un cliente es crítico', max_digits=5)),
                ('umbral_moderado', models.DecimalField(decimal_places=2, default=2, help_text='Tasa desde la cual un cliente es moderado (hasta el umbral crítico)', max_digits=5)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración del tablero',
                'verbose_name_plural': 'configuración del tablero',
            },
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'coordinadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'sectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('clase_riesgo', models.PositiveSmallIntegerField(help_text='1 = menor riesgo, 5 = mayor riesgo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('activo', models.BooleanField(default=True)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='tablero.coordinador')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='tablero.sector')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes')),
                ('trabajadores_activos', models.PositiveIntegerField()),
                ('casos', models.PositiveIntegerField(default=0)),
                ('casos_graves', models.PositiveIntegerField(default=0)),
                ('costo_leve', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('costo_grave', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='tablero.cliente')),
            ],
            options={
                'verbose_name': 'indicador mensual',
                'verbose_name_plural': 'indicadores mensuales',
                'ordering': ['periodo', 'cliente'],
                'permissions': [('ver_tablero', 'Puede ver el tablero de monitoreo'), ('ver_todos_los_clientes', 'Puede ver todos los clientes (sin restricción por coordinador)'), ('exportar_datos', 'Puede exportar datos del tablero')],
                'indexes': [models.Index(fields=['periodo'], name='tablero_ind_periodo_b3c66b_idx')],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'periodo'), name='indicador_unico_cliente_periodo'), models.CheckConstraint(condition=models.Q(('casos_graves__lte', models.F('casos'))), name='indicador_graves_menor_igual_casos'), models.CheckConstraint(condition=models.Q(('trabajadores_activos__gt', 0)), name='indicador_trabajadores_positivos')],
            },
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('clase_riesgo__gte', 1), ('clase_riesgo__lte', 5)), name='cliente_clase_riesgo_1_5'),
        ),
    ]
