# Generated by Django 5.2.17 on 2026-09-25 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_corte', models.DateField(help_text='Último día con datos en la fuente')),
                ('periodo_desde', models.DateField()),
                ('periodo_hasta', models.DateField(help_text='Último mes cerrado cargado')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('variables', models.JSONField(default=list, help_text='Variables opcionales disponibles en esta carga')),
                ('calidad', models.JSONField(default=dict, help_text='Hallazgos de calidad detectados al cargar')),
            ],
            options={
                'verbose_name': 'carga de datos',
                'verbose_name_plural': 'cargas de datos',
                'ordering': ['-creada'],
            },
        ),
        migrations.AlterModelOptions(
            name='indicadormensual',
            options={'ordering': ['periodo', 'cliente'], 'permissions': [('ver_tablero', 'Puede ver el tablero de monitoreo'), ('ver_todos_los_clientes', 'Puede ver todos los clientes (sin restricción por coordinador)'), ('exportar_datos', 'Puede exportar datos del tablero'), ('ver_analisis', 'Puede ver el análisis gerencial y el diagnóstico'), ('ver_calidad_datos', 'Puede ver el reporte de calidad de datos')], 'verbose_name': 'indicador mensual', 'verbose_name_plural': 'indicadores mensuales'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_vinculacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='regional',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='indicadormensual',
            name='actividades_prevencion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadormensual',
            name='casos_abiertos',
            field=models.PositiveIntegerField(blank=True, help_text='De los casos del mes, cuántos siguen abiertos a la fecha de corte', null=True),
        ),
        migrations.AddField(
            model_name='indicadormensual',
            name='casos_anulados',
            field=models.PositiveIntegerField(blank=True, help_text='Registros anulados (no cuentan como casos)', null=True),
        ),
        migrations.AddField(
            model_name='indicadormensual',
            name='casos_graves_abiertos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadormensual',
            name='dias_ausencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadormensual',
            name='participantes_prevencion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadormensual',
            name='valor_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_origen', models.PositiveIntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('leve', 'Leve'), ('grave', 'Grave')], max_length=10)),
                ('dias_ausencia', models.PositiveIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado')], max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='tablero.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['cliente', 'fecha'], name='tablero_cas_cliente_2d3cd0_idx')],
            },
        ),
    ]
