# Generated by Django 5.2.17 on 2026-09-28 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Para qué se usa, p. ej. «n8n - chat de prueba»', max_length=80)),
                ('huella', models.CharField(editable=False, max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuario', models.ForeignKey(help_text='El agente verá solo lo que este usuario puede ver', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_agente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token del agente',
                'verbose_name_plural': 'tokens del agente',
                'ordering': ['-creado'],
            },
        ),
    ]
